apiVersion: v1
kind: Pod
metadata:
  name: dlltagent
  namespace: default345
spec:
  tolerations:
  # these tolerations are to have the daemonset runnable on control plane nodes
  # remove them if your control plane nodes should not run pods
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
  hostNetwork: true
  hostPID: true
  containers:
  - name: dllt-agent
    image: rodolk/dlltagent:v1
    imagePullPolicy: Always
    securityContext:
      privileged: true
    env:
      - name: SEARCH_HTTP_HEADER
        value: "X-Pepe"
      - name: FOLLOW_PORT
        value: "6060"
      - name: INTERFACE_INDEX_SNIF
        value: "345345345"
      - name: AVOID_LIVENESS_PROBE
        value: "345AVOID_LIVENESS_PROBE345"
      - name: USE_EBPF
        value: "N"
      - name: MEJOR_EQUIPO
        value: "Talleres"
      - name: AUTHOR
        value: "rodolk"
    volumeMounts:
      - name: debug
        mountPath: /sys/kernel/debug
      - name: bpf
        mountPath: /sys/fs/bpf
      - name: cgroup
        mountPath: /sys/fs/cgroup
      - name: tmp
        mountPath: /tmp
      - name: dlltuser
        mountPath: /dllt/logs
  nodeName: changeNodeName
  volumes:
  - name: bpf
    hostPath:
      path: /sys/fs/bpf
  - name: cgroup
    hostPath:
      path: /sys/fs/cgroup
  - name: debug
    hostPath:
      path: /sys/kernel/debug
  - name: dlltuser
    hostPath:
      path: /dllt/logs
  - name: tmp
    emptyDir: {}
  terminationGracePeriodSeconds: 60
  


